default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: brasileirao_development

test:
  <<: *default
  database: brasileirao_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
