default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: lucas123
  host: localhost

development:
  <<: *default
  database: brasileirao_development

test:
  <<: *default
  database: brasileirao_test

production:
  <<: *default
  database: brasileirao_production
  username: lucas_producao
  password: <%= ENV['DATABASE_PASSWORD'] %>